### ISSUE TITLE
SWIFT catalogue web interface: add new nowcasting interface to catalogue website

### ISSUE THREAD

**Issue by tdjames1** [cemac/SWIFT-Testbed3#32]
Replace existing summary page with new nowcasting interface (#19)

**TODO**
- [x] Get past observed as well as current/forecast images
Currently the ResourcesController summary method pulls out the latest image, plus forecast images if available. We'll also want observation images going back some number of hours (e.g. 6 hours).
- [x] #59
The static mockup defines a pre-populated manifest of image locations which are then loaded as required. Either need to do this for all product categories to be displayed or changing the select needs to trigger an action to return a manifest for the selected category (N.B. this would need to be fixed to the current display time).
- [x] #58
- [x] Ensure that filename parsing handles non NWCSAF categories (e.g. #56 and #57)
- [x] Get subset of categories for resource selector
Need to get subset of categories (https://github.com/cemac/SWIFT-Testbed3/issues/24) for display in dropdown for switching resources.
- [ ] Ensure number of forward/backward time steps to be displayed can be adjusted as required
- [ ] Ensure required categories to be displayed can be adjusted as required

**Comment by tdjames1** [comment]
Initial work on integration done and checked in to swift catalogue repo on BB as `swift-gateway` branch. Some further work needed to address the above points.

**Comment by tdjames1** [comment]
Test version of catalogue, with cake3 backend and Tamora's new summary pages is now live:
https://science.ncas.ac.uk/swift-test

**TODO**
- [ ] Resolve time offset issues caused by different generation times for some products e.g. RDT
- [ ] Do not show categories if no resources are available

**Comment by tdjames1** [comment]
Modifications to handle MSG images in PR https://bitbucket.org/ncas_it/catalogue/pull-requests/5.

**Comment by tdjames1** [comment]
Nowcasting interface is now live on swift website.
